server:
  port: 8763

spring:
  application:
    name: SERVICE-PROVIDER

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    username: root
    password: ok

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8071/eureka
mybatis:
  mapper-locations: classpath:mappers/*.xml
#logging:
#  level:
#    com.zb.sp.dao: debug
