server:
  port: 8765

spring:
  application:
    name: CONSUMER OF FEIGN
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8071/eureka


